version: '3.5'

services:
        timetracker:
            build: 
                context: .
                dockerfile: Dockerfile
            volumes:
                - ./config.json:/app/config.json
